# Generated by Django 5.2.6 on 2025-09-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Gala_Pandu_Pandu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(help_text='Coloque aqui o emoji ou código do ícone (ex: 🎨, 📚, ⚽)', max_length=10)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['titulo'],
            },
        ),
    ]
