# Generated by Django 5.2.4 on 2025-09-26 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Gala_Pandu_Pandu', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='app_Gala_Pandu_Pandu.categoria')),
                ('usuario', models.OneToOneField(limit_choices_to={'tipo': 'candidato'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='app_Gala_Pandu_Pandu.candidato')),
                ('votante', models.ForeignKey(limit_choices_to={'tipo': 'votante'}, on_delete=django.db.models.deletion.CASCADE, related_name='votos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('votante', 'candidato')},
            },
        ),
    ]
