# Generated by Django 5.2.4 on 2025-09-26 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Gala_Pandu_Pandu', '0003_candidato_voto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='data',
            new_name='criado_em',
        ),
        migrations.AlterUniqueTogether(
            name='candidato',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='voto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_Gala_Pandu_Pandu.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'tipo': 'candidato'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voto',
            name='votante',
            field=models.ForeignKey(limit_choices_to={'tipo': 'votante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together={('votante', 'categoria')},
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='biografia',
        ),
    ]
